apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xpq8lmr0e-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xpq8lmr0e-dotnet-basic-gitops